OrdersApp.WebApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using OrdersApp.WebApi.Areas.HelpPage.ModelDescriptions;
using OrdersApp.WebApi.Areas.HelpPage.Models;

namespace OrdersApp.WebApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

OrdersApp.WebApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using log4net;
using OrdersApp.Data;
using OrdersApp.ViewModels;

namespace OrdersApp.WebApi.Controllers
{
    public class HomeController : Controller
    {
        private static readonly ILog Log;
        public ActionResult Index()
        {
            ViewBag.Title = "OrderApp Home Page";

            try
            {
                var orderAppDbContext = new OrdersAppDbContext();

                var customers = orderAppDbContext.Customer.ToList();

                var list = new List<CustomerViewModel>();
                foreach (var item in customers)
                {
                    var returnCustomer = new CustomerViewModel
                    {
                        CustomerId = item.CustomerId,
                        Email = item.Email,
                        Name = item.Name
                    };
                    list.Add(returnCustomer);
                }
 
                return View(list);
            }
            catch (Exception exception)
            {
                Log.Error(exception);
                throw;
            }
        }
    }
}

OrdersApp.WebApi/Views/Home/Index.cshtml
@model List<OrdersApp.ViewModels.CustomerViewModel>
<div class="jumbotron">
    <h1>OrdersApp</h1>
    <p class="lead">See OrdersApp WebApi endpoints.</p>
    <p>@Html.ActionLink("OrdersApp API", "Index", "Help", new { area = "" }, null)</p>
</div>
 
<div class="page-header">
    <h1>OrdersApp Services</h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">List of all customers</h2>
            </div>
            <div class="panel-body">
                <ul class="list-unstyled">
                @foreach (var item in Model)
                {
 
                            <li>
                                <strong>@item.Name</strong>: <span>@item.Email</span>
                            </li>
                      
                }
                </ul> 
            </div>
        </div>
       
    </div>

    <div class="col-md-4">
        <!-- TODO: Book details -->
    </div>

    <div class="col-md-4">
        <!-- TODO: Add new book -->
    </div>
</div>